# -*- coding: utf-8 -*-
"""add_numbers.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_SuTKU20tne1aKa_ORoKQ3UxAOM5Pg21
"""

def add(a,b):
 return a+b

sum = add (10,5)
print(sum)