# -*- coding: utf-8 -*-
"""greet_user.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_SuTKU20tne1aKa_ORoKQ3UxAOM5Pg21
"""

def greeting():
 return print("hi")

greeting()