# -*- coding: utf-8 -*-
"""multiply.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_SuTKU20tne1aKa_ORoKQ3UxAOM5Pg21
"""

def multiply(a, b):
  return a*b

product = multiply(10, 5)
print(product)