# -*- coding: utf-8 -*-
"""new_feature.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_SuTKU20tne1aKa_ORoKQ3UxAOM5Pg21
"""

def subtract(a, b):
  return a-b

difference = subtract(10, 5)
print(difference)